import { z } from "zod";
import { futureDate, optionalEmail, optionalPhone, phone } from "./common.js";

export const pharmacySchema = z.object({
  pharmacyName: z.string().min(2),
  ownerName: z.string().min(2),
  mobile: phone,
  whatsappNumber: optionalPhone,
  email: optionalEmail,
  city: z.string().min(2),
  area: z.string().min(2),
  address: z.string().optional(),
  pincode: z.string().optional(),
  drugLicenseNumber: z.string().optional(),
  drugLicenseStatus: z.string().default("Pending"),
  gstNumber: z.string().optional(),
  gstStatus: z.string().default("Pending"),
  currentBusinessType: z.string().optional(),
  monthlyOrderPotential: z.coerce.number().nonnegative().optional(),
  onboardingStage: z.string().default("New"),
  leadSource: z.string().optional(),
  leadPriority: z.string().default("MEDIUM"),
  assignedTo: z.string().optional(),
  nextFollowUpDate: futureDate,
  remarks: z.string().optional(),
  status: z.string().default("NEW"),
});

export const deliverySchema = z.object({
  fullName: z.string().min(2),
  mobile: phone,
  whatsappNumber: optionalPhone,
  city: z.string().min(2),
  area: z.string().min(2),
  address: z.string().optional(),
  vehicleType: z.string().optional(),
  vehicleNumber: z.string().optional(),
  drivingLicenseNumber: z.string().optional(),
  drivingLicenseStatus: z.string().default("Pending"),
  aadhaarStatus: z.string().default("Pending"),
  policeVerificationStatus: z.string().default("Not Started"),
  trainingStatus: z.string().default("Not Started"),
  preferredWorkingTime: z.string().optional(),
  onboardingStage: z.string().default("New"),
  assignedTo: z.string().optional(),
  nextFollowUpDate: futureDate,
  remarks: z.string().optional(),
  status: z.string().default("NEW"),
});

export const b2bSchema = z.object({
  businessName: z.string().min(2),
  contactPerson: z.string().min(2),
  mobile: phone,
  whatsappNumber: optionalPhone,
  email: optionalEmail,
  businessType: z.string().min(2),
  city: z.string().min(2),
  area: z.string().min(2),
  address: z.string().optional(),
  requirementType: z.string().optional(),
  expectedMonthlyPurchase: z.coerce.number().nonnegative().optional(),
  dealValue: z.coerce.number().nonnegative().optional(),
  quotationStatus: z.string().default("Not Sent"),
  negotiationStage: z.string().default("New"),
  leadSource: z.string().optional(),
  assignedTo: z.string().optional(),
  nextFollowUpDate: futureDate,
  remarks: z.string().optional(),
  status: z.string().default("NEW"),
});
